--EXECUTER CE SCRIPT AU CAS DE NOUVEAU DEPOT
INSERT INTO F_DEPOT_DEDIE (DE_NO, AUTHORIZED, PROT_Guid)
SELECT DISTINCT 
    35 AS DE_NO, --RECUPEREZ LE DE_No DU NOUVEAU DEPOT DANS F_DEPOT
    0 AS AUTHORIZED,
    p.PROT_Guid    
FROM 
    F_DEPOT d
CROSS JOIN 
    F_PROTECTIONCIAL p