// <auto-generated />
namespace arbioApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class f_devise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f_devise));
        
        string IMigrationMetadata.Id
        {
            get { return "202510150758469_f_devise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
