// <auto-generated />
namespace arbioApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class F_DOCFRAISIMPORT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(F_DOCFRAISIMPORT));
        
        string IMigrationMetadata.Id
        {
            get { return "202510131145338_F_DOCFRAISIMPORT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
