CREATE TABLE dbo.F_DEPOT_DEDIE (
  ID int IDENTITY(1, 1) NOT NULL,
  DE_NO int NULL,
  AUTHORIZED bit NULL,
  PROT_Guid uniqueidentifier NULL,
  PRIMARY KEY CLUSTERED (ID)
    WITH (
      PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF,
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
ON [PRIMARY]
GO