--EXECUTEZ CE SCRIPT AU CAS Où UN UTILISATEUR N'A PAS INSCRIT DANS UN DEPOT
INSERT INTO F_DEPOT_DEDIE (DE_NO, PROT_Guid, AUTHORIZED)
SELECT 
    d.DE_NO, 
    p.PROT_Guid, 
    0 -- AUTHORIZED par défaut
FROM 
    F_DEPOT d
CROSS JOIN 
    F_PROTECTIONCIAL p
WHERE 
    NOT EXISTS (
        SELECT 1 
        FROM F_DEPOT_DEDIE dd
        WHERE dd.DE_NO = d.DE_NO
          AND dd.PROT_Guid = p.PROT_Guid
    );
